apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  subdomain: mysql
  hostname: mysql-pod