apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    volumemounts:
    - mountPath: /var/lib/mysql
      name: data-volume
  volume:
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-volume
